import 'dart:io';
import 'package:get/get.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:quickalert/quickalert.dart';
import '../../../data/providers/service_provider.dart';
import '../../../data/models/service_model.dart';

class ServiceController extends GetxController {
  final ServicesProvider _serviceProvider = Get.find();
  final ImagePicker _imagePicker = ImagePicker();

  final services = <ServiceModel>[].obs;
  final isLoading = false.obs;

  // Image picker state
  final Rx<File?> selectedImage = Rx<File?>(null);
  final RxString currentImageUrl = ''.obs;

  // Form controllers
  final nameController = TextEditingController();
  final descriptionController = TextEditingController();
  final priceController = TextEditingController();
  final durationController = TextEditingController();

  @override
  void onInit() {
    super.onInit();
    fetchServices();
  }

  @override
  void onClose() {
    nameController.dispose();
    descriptionController.dispose();
    priceController.dispose();
    durationController.dispose();
    super.onClose();
  }

  Future<void> fetchServices() async {
    try {
      isLoading.value = true;
      final result = await _serviceProvider.getServices();
      services.assignAll(result);
    } catch (e) {
      rethrow;
    } finally {
      isLoading.value = false;
    }
  }

  Future<void> pickImageFromGallery() async {
    try {
      final XFile? pickedFile = await _imagePicker.pickImage(
        source: ImageSource.gallery,
        maxWidth: 1024,
        maxHeight: 1024,
        imageQuality: 80,
      );
      if (pickedFile != null) {
        selectedImage.value = File(pickedFile.path);
      }
    } catch (e) {
      rethrow;
    }
  }

  Future<void> pickImageFromCamera() async {
    try {
      final XFile? pickedFile = await _imagePicker.pickImage(
        source: ImageSource.camera,
        maxWidth: 1024,
        maxHeight: 1024,
        imageQuality: 80,
      );
      if (pickedFile != null) {
        selectedImage.value = File(pickedFile.path);
      }
    } catch (e) {
      rethrow;
    }
  }

  void removeSelectedImage() {
    selectedImage.value = null;
    currentImageUrl.value = '';
  }

  void showImageSourceDialog() {
    Get.bottomSheet(
      Container(
        padding: const EdgeInsets.all(20),
        decoration: const BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              'Select Image Source',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 20),
            ListTile(
              leading: const Icon(Icons.photo_library, color: Colors.blue),
              title: const Text('Gallery'),
              onTap: () {
                Get.back();
                pickImageFromGallery();
              },
            ),
            ListTile(
              leading: const Icon(Icons.camera_alt, color: Colors.green),
              title: const Text('Camera'),
              onTap: () {
                Get.back();
                pickImageFromCamera();
              },
            ),
            if (selectedImage.value != null || currentImageUrl.value.isNotEmpty)
              ListTile(
                leading: const Icon(Icons.delete, color: Colors.red),
                title: const Text('Remove Image'),
                onTap: () {
                  Get.back();
                  removeSelectedImage();
                },
              ),
          ],
        ),
      ),
    );
  }

  Future<void> createService() async {
    if (!_validateForm()) return;

    try {
      isLoading.value = true;

      String? imageUrl;

      // Upload image if selected
      if (selectedImage.value != null) {
        final fileName = '${DateTime.now().millisecondsSinceEpoch}.jpg';
        imageUrl = await _serviceProvider.uploadServiceImage(
          selectedImage.value!,
          fileName,
        );
      }

      final newService = ServiceModel(
        id: '', // Will be auto-generated by Supabase
        name: nameController.text.trim(),
        description: descriptionController.text.trim(),
        pricePerKg: int.parse(priceController.text.trim()),
        duration: durationController.text.trim(),
        imageUrl: imageUrl,
      );

      await _serviceProvider.createService(newService);

      Get.back();
      clearForm();
      fetchServices();

      QuickAlert.show(
        context: Get.context!,
        type: QuickAlertType.success,
        title: 'Sukkses',
        text: 'Layanan berhasil ditambahkan',
      );
    } catch (e) {
      QuickAlert.show(
        context: Get.context!,
        type: QuickAlertType.error,
        title: 'Gagal',
        text: 'Gagal menambahkan layanan: $e',
      );
    } finally {
      isLoading.value = false;
    }
  }

  Future<void> updateService(ServiceModel service) async {
    if (!_validateForm()) return;

    try {
      isLoading.value = true;

      String? imageUrl = service.imageUrl;

      // Upload new image if selected
      if (selectedImage.value != null) {
        final fileName = '${DateTime.now().millisecondsSinceEpoch}.jpg';
        imageUrl = await _serviceProvider.uploadServiceImage(
          selectedImage.value!,
          fileName,
        );

        // Delete old image if exists
        if (service.imageUrl != null && service.imageUrl!.isNotEmpty) {
          await _serviceProvider.deleteServiceImage(service.imageUrl!);
        }
      }

      // If image was removed
      if (currentImageUrl.value.isEmpty && service.imageUrl != null) {
        await _serviceProvider.deleteServiceImage(service.imageUrl!);
        imageUrl = null;
      }

      final updatedService = service.copyWith(
        name: nameController.text.trim(),
        description: descriptionController.text.trim(),
        pricePerKg: int.parse(priceController.text.trim()),
        duration: durationController.text.trim(),
        imageUrl: imageUrl,
      );

      await _serviceProvider.updateService(updatedService);

      Get.back();
      clearForm();
      fetchServices();

      QuickAlert.show(
        context: Get.context!,
        type: QuickAlertType.success,
        title: 'Sukkses',
        text: 'Layanan berhasil diperbarui',
      );
    } catch (e) {
      QuickAlert.show(
        context: Get.context!,
        type: QuickAlertType.error,
        title: 'Gagal',
        text: 'Gagal memperbarui layanan: $e',
      );
    } finally {
      isLoading.value = false;
    }
  }

  Future<void> deleteService(
    String id,
    String serviceName, {
    String? imageUrl,
  }) async {
    QuickAlert.show(
      context: Get.context!,
      type: QuickAlertType.confirm,
      title: 'Delete Service',
      text: 'Are you sure you want to delete "$serviceName"?',
      confirmBtnText: 'Delete',
      cancelBtnText: 'Cancel',
      confirmBtnColor: Colors.red,
      onConfirmBtnTap: () async {
        Get.back();

        try {
          isLoading.value = true;

          // Delete image from storage if exists
          if (imageUrl != null && imageUrl.isNotEmpty) {
            await _serviceProvider.deleteServiceImage(imageUrl);
          }

          await _serviceProvider.deleteService(id);
          fetchServices();

          QuickAlert.show(
            context: Get.context!,
            type: QuickAlertType.success,
            title: 'Sukkses',
            text: 'Layanan berhasil dihapus',
          );
        } catch (e) {
          QuickAlert.show(
            context: Get.context!,
            type: QuickAlertType.error,
            title: 'Gagal',
            text: 'Gagal menghapus layanan: $e',
          );
        } finally {
          isLoading.value = false;
        }
      },
    );
  }

  void editService(ServiceModel service) {
    nameController.text = service.name;
    descriptionController.text = service.description;
    priceController.text = service.pricePerKg.toString();
    durationController.text = service.duration;
    currentImageUrl.value = service.imageUrl ?? '';
    selectedImage.value = null;
  }

  void clearForm() {
    nameController.clear();
    descriptionController.clear();
    priceController.clear();
    durationController.clear();
    selectedImage.value = null;
    currentImageUrl.value = '';
  }

  bool _validateForm() {
    if (nameController.text.trim().isEmpty) {
      _showValidation('Service name is required');
      return false;
    }

    if (priceController.text.trim().isEmpty ||
        int.tryParse(priceController.text.trim()) == null) {
      _showValidation('Valid price is required');
      return false;
    }

    if (durationController.text.trim().isEmpty) {
      _showValidation('Duration is required');
      return false;
    }

    return true;
  }

  void _showValidation(String message) {
    Get.snackbar(
      'Validation Error',
      message,
      backgroundColor: Colors.orange,
      colorText: Colors.white,
    );
  }
}
