// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkptHgIvNuWyqyj4xeR08D4898b1laavQ',
    appId: '1:984071798598:web:2738ee0c2b9f530311ef47',
    messagingSenderId: '984071798598',
    projectId: 'cemerlaund',
    authDomain: 'cemerlaund.firebaseapp.com',
    storageBucket: 'cemerlaund.firebasestorage.app',
    measurementId: 'G-XPMSJERCRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFlB4LFXuICgbxfkaHnY87lzzJZD5muEc',
    appId: '1:984071798598:android:70618bfa805e0b9e11ef47',
    messagingSenderId: '984071798598',
    projectId: 'cemerlaund',
    storageBucket: 'cemerlaund.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBv9v4D14yZCcSuFESDWFV_na3wvyn9D4',
    appId: '1:984071798598:ios:4f724a7650c737bb11ef47',
    messagingSenderId: '984071798598',
    projectId: 'cemerlaund',
    storageBucket: 'cemerlaund.firebasestorage.app',
    iosBundleId: 'com.example.laundrymobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBv9v4D14yZCcSuFESDWFV_na3wvyn9D4',
    appId: '1:984071798598:ios:4f724a7650c737bb11ef47',
    messagingSenderId: '984071798598',
    projectId: 'cemerlaund',
    storageBucket: 'cemerlaund.firebasestorage.app',
    iosBundleId: 'com.example.laundrymobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkptHgIvNuWyqyj4xeR08D4898b1laavQ',
    appId: '1:984071798598:web:168307dba851e0ab11ef47',
    messagingSenderId: '984071798598',
    projectId: 'cemerlaund',
    authDomain: 'cemerlaund.firebaseapp.com',
    storageBucket: 'cemerlaund.firebasestorage.app',
    measurementId: 'G-9FE0QE67LX',
  );

}