// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl2T3yPoT_N7tKs7PggMMwqR7aqNUpGaA',
    appId: '1:561748156690:web:3fba0fe215c03b324313cb',
    messagingSenderId: '561748156690',
    projectId: 'mobilelaundry-2f460',
    authDomain: 'mobilelaundry-2f460.firebaseapp.com',
    storageBucket: 'mobilelaundry-2f460.firebasestorage.app',
    measurementId: 'G-PD5MJ48CHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmb1Zt7iTU3diO0Mmn_RRj85LRdnfv4mU',
    appId: '1:561748156690:android:005cce42cd137ccb4313cb',
    messagingSenderId: '561748156690',
    projectId: 'mobilelaundry-2f460',
    storageBucket: 'mobilelaundry-2f460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB53dDtY_VP5K1lGI36zl3EdwMhc_Ox0Yk',
    appId: '1:561748156690:ios:32fa0734f07deebc4313cb',
    messagingSenderId: '561748156690',
    projectId: 'mobilelaundry-2f460',
    storageBucket: 'mobilelaundry-2f460.firebasestorage.app',
    iosBundleId: 'com.example.laundrymobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB53dDtY_VP5K1lGI36zl3EdwMhc_Ox0Yk',
    appId: '1:561748156690:ios:32fa0734f07deebc4313cb',
    messagingSenderId: '561748156690',
    projectId: 'mobilelaundry-2f460',
    storageBucket: 'mobilelaundry-2f460.firebasestorage.app',
    iosBundleId: 'com.example.laundrymobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl2T3yPoT_N7tKs7PggMMwqR7aqNUpGaA',
    appId: '1:561748156690:web:c7a3929dc63cac9a4313cb',
    messagingSenderId: '561748156690',
    projectId: 'mobilelaundry-2f460',
    authDomain: 'mobilelaundry-2f460.firebaseapp.com',
    storageBucket: 'mobilelaundry-2f460.firebasestorage.app',
    measurementId: 'G-BJ2Z08GTE7',
  );
}
